export const ConfigKeyWords = ["_NAME_", "_RETURN_", "_CONTEXT_", "_CONTINUE_"];

export const nodeKeywords = new Set([
  // JavaScript/Node.js keywords
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",

  // Additional Node.js/ECMAScript-specific keywords
  "async",
  "await",
  "arguments",
  "eval",
  "of",

  // Reserved but may not yet be used in JavaScript
  "enum",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
  "static",
]);
